# Welcome to Jekyll!
#

# Site settings
title: Not just data science 
description: Antonella Succurro, PhD
owner: Antonella Succurro, PhD
first_published: 2022
email: a.succurro@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asuccurro.github.io/" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/a_succurro
  github: https://github.com/asuccurro
  linkedin-square: https://linkedin.com/in/asuccurro/
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
